/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author NSH
 */
public class Sign_up extends javax.swing.JFrame {
    static int Icode = 1;

    /**
     * Creates new form Sign_up
     */
    public Sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtname = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        PW_Check = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Duplication = new javax.swing.JButton();
        Signup = new javax.swing.JButton();
        txtid = new javax.swing.JLabel();
        txtpw = new javax.swing.JLabel();
        txtpwcheck = new javax.swing.JLabel();
        txtsignup = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        PW = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtname.setText("성 명");

        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDKeyTyped(evt);
            }
        });

        PW_Check.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PW_CheckKeyTyped(evt);
            }
        });

        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });

        Duplication.setText("중복확인");
        Duplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuplicationActionPerformed(evt);
            }
        });

        Signup.setText("회원 가입");
        Signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupActionPerformed(evt);
            }
        });

        txtid.setText("아이디");

        txtpw.setText("비밀번호");

        txtpwcheck.setText("비밀번호 확인");

        txtsignup.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        txtsignup.setText("회원가입");

        Back.setText("뒤로가기");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        PW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PWKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Signup))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtpwcheck)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtpw)
                                        .addComponent(txtid, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(PW_Check, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(ID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PW))
                                .addGap(18, 18, 18)
                                .addComponent(Duplication)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(txtsignup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtsignup)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Duplication))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpw)
                    .addComponent(PW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpwcheck)
                    .addComponent(PW_Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Signup)
                    .addComponent(Back))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // 뒤로가기 버튼
        setVisible((false));
        new Login().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDKeyTyped
        //엔터치면 다음 텍스트 필드로 넘어가기
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            PW.requestFocus();
        }
    }//GEN-LAST:event_IDKeyTyped

    private void PWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PWKeyTyped
        //엔터치면 다음 텍스트 필드로 넘어가기
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            PW_Check.requestFocus();
        }
    }//GEN-LAST:event_PWKeyTyped

    private void PW_CheckKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PW_CheckKeyTyped
        //엔터치면 다음 텍스트 필드로 넘어가기
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            Name.requestFocus();
        }
    }//GEN-LAST:event_PW_CheckKeyTyped

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
        //엔터치면 회원가입 버튼으로 넘어가기
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            Signup.doClick();
        }
    }//GEN-LAST:event_NameKeyTyped

    private void SignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupActionPerformed
        //회원가입 버튼 누르면 파일로 아이디 비번 이름 저장하기
        String id = ID.getText();
        String password = PW.getText();
        String pwcheck = PW_Check.getText();
        String name = Name.getText();
        
        BufferedWriter writer = null;
        
        try{
            if((id.equals("")||password.equals(""))||(pwcheck.equals("")||name.equals(""))){
                JOptionPane.showMessageDialog(this,"정확히 입력해주세요");
                throw new IOException();
            }else if(isDuplicate(id)){
                JOptionPane.showMessageDialog(this,"중복된 아이디가 있습니다.");
                throw new IOException();
            }else if(!password.equals(pwcheck)){
                JOptionPane.showMessageDialog(this,"비밀번호가 틀렸습니다.");
                throw new IOException();
            }
            writer = new BufferedWriter(new FileWriter("C:\\Users\\NSH\\Documents\\user.txt", true));
            idcode(Icode);
            writer.write(id+" "+password+" "+name+" "+Icode);
            writer.newLine();
            writer.close();
            JOptionPane.showMessageDialog(this,"회원가입 완료.");
            setVisible(false);
            new Login().setVisible(true);           
            
        }catch(IOException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "회원가입 안됨");
        }
    }//GEN-LAST:event_SignupActionPerformed

    private void DuplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuplicationActionPerformed
        // TODO add your handling code here:
        String id = ID.getText();
        
        if(isDuplicate(id)){
            JOptionPane.showMessageDialog(this, "이미 존재하는 아이디입니다.");
        }else{
            JOptionPane.showMessageDialog(this, "사용 가능한 아이디입니다.");
        }
    }//GEN-LAST:event_DuplicationActionPerformed

    
    private boolean isDuplicate(String id){     //중복된 아이디가 있는지 확인하는 메소드
        try(BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\NSH\\Documents\\user.txt"))){//파일에서 가져오기
            String line;
            while((line = reader.readLine()) != null){ //텍스트 파일 null이 될때까지 전부 읽기
                String[] userInfo = line.split(" ");//userInfo배열 만들어서 띄어쓰기별로 배열 인덱스 부여
                if(userInfo.length >= 1 && userInfo[0].equals(id)){
                    return true;    //중복된 ID 존재
                }                
            }
            
        }catch(IOException ex){
            ex.printStackTrace();
        }
        return false;//중복된 id가 없음
    }
    
    private void idcode(int iden){
        try(BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\NSH\\Documents\\user.txt"))){//파일에서 가져오기
            String line;
            while((line = reader.readLine()) != null){ //텍스트 파일 null이 될때까지 전부 읽기
                String[] userInfo = line.split(" ");//userInfo배열 만들어서 띄어쓰기별로 배열 인덱스 부여
                if(userInfo.length >= 1){
                    if(!userInfo[3].equals(iden)){
                        Icode = Integer.parseInt(userInfo[3]);
                        Icode++;
                    }
                }                
            }
        }catch(IOException ex){
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Duplication;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PW;
    private javax.swing.JTextField PW_Check;
    private javax.swing.JButton Signup;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtname;
    private javax.swing.JLabel txtpw;
    private javax.swing.JLabel txtpwcheck;
    private javax.swing.JLabel txtsignup;
    // End of variables declaration//GEN-END:variables
}
